# Generated by Django 6.0.5 on 2026-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
