# Generated by Django 6.0.5 on 2026-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.AlterField(
            model_name='deals',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
