# Generated by Django 6.0.5 on 2026-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_deals_options_alter_deals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='date',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
    ]
