# Generated by Django 6.0.5 on 2026-05-16 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_deals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
