# Generated by Django 6.0.5 on 2026-05-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_user_deals_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Dealer',
        ),
        migrations.RenameField(
            model_name='deals',
            old_name='user',
            new_name='dealer',
        ),
    ]
