# Generated by Django 6.0.5 on 2026-05-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_rename_user_dealer_rename_user_deals_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.dealer'),
        ),
    ]
